# Generated by Django 5.1.1 on 2024-09-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productentry_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductEntry',
            new_name='Product',
        ),
    ]
